title: "Fatimatou Tambadou"
logo: /img/my.jpeg
description: "Portfolio d'une Ingénieure en Intelligence Artificielle & Big Data spécialisée en IA Générative, RAG et Assistants IA."
show_downloads: true
theme: jekyll-theme-minimal
lang: fr
